spring:
  datasource:
    url: jdbc:mysql:///size_design?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    password: qing1016..
    password: Root123!!
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  jpa:
    show-sql: true
server:
  port: 8088
  servlet:
    context-path: /manage